name: launcher_kit
description: UIkit-inspired component library for Flutter — layout, elements, forms, and components.
publish_to: 'none'

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
